<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceArSeeder extends Seeder
{
    public function run()
    {
        // Get category IDs by slug
        $categories = DB::table('service_categories')->pluck('id', 'slug');

        DB::table('services_ar')->insert([
            // Hajj Application Process
            [
                'slug' => 'visit-agent',
                'name' => 'زيارة الوكيل',
                'description' => 'قم بزيارة وكلاء الحج المعتمدين لدينا لبدء عملية التقديم. سيرشدك وكلاؤنا ذوو الخبرة خلال جميع المتطلبات والوثائق اللازمة لرحلة الحج.',
                'price' => 0.00,
                'image_url' => '/services/visit_agent.jpg',
                'category_id' => $categories['hajj-application'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'prepare-documents',
                'name' => 'تحضير الوثائق',
                'description' => 'جمع وتحضير جميع الوثائق الضرورية بما في ذلك جواز السفر والشهادات الطبية وسجلات التطعيم والإثبات المالي المطلوب لطلب الحج.',
                'price' => 50.00,
                'image_url' => '/services/prepare_documents.jpg',
                'category_id' => $categories['hajj-application'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'payment-method',
                'name' => 'إعداد طريقة الدفع',
                'description' => 'تكوين طرق دفع آمنة لباقة الحج الخاصة بك بما في ذلك الإقامة والنقل والخدمات الأخرى. خيارات دفع متعددة متاحة.',
                'price' => 0.00,
                'image_url' => '/services/payment_method.jpg',
                'category_id' => $categories['hajj-application'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'setup-hotel',
                'name' => 'إعداد الفندق',
                'description' => 'احجز وقم بتكوين إقامتك في مكة والمدينة. اختر من فئات فنادق مختلفة بناءً على القرب من الحرم والمرافق.',
                'price' => 1500.00,
                'image_url' => '/services/setup_hotel.jpg',
                'category_id' => $categories['hajj-application'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],

            // Terms and Policies for Hajj
            [
                'slug' => 'hajj-guidelines',
                'name' => 'إرشادات وقواعد الحج',
                'description' => 'إرشادات شاملة لأداء الحج وفقاً للمبادئ الإسلامية واللوائح السعودية. تشمل قواعد اللباس وإرشادات السلوك والمواد المحظورة.',
                'price' => 0.00,
                'image_url' => '/services/hajj_guidelines.jpg',
                'category_id' => $categories['terms-policies'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'visa-requirements',
                'name' => 'متطلبات التأشيرة',
                'description' => 'معلومات مفصلة حول متطلبات تأشيرة الحج وعملية التقديم وفترة الصلاحية ولوائح الدخول للدول المختلفة.',
                'price' => 200.00,
                'image_url' => '/services/visa_requirements.jpg',
                'category_id' => $categories['terms-policies'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'health-regulations',
                'name' => 'لوائح الصحة والسلامة',
                'description' => 'متطلبات صحية مهمة تشمل التطعيمات الإجبارية والتأمين الصحي والفحوصات الطبية وبروتوكولات السلامة أثناء الحج.',
                'price' => 0.00,
                'image_url' => '/services/health_regulations.jpg',
                'category_id' => $categories['terms-policies'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'financial-policies',
                'name' => 'السياسات المالية',
                'description' => 'فهم جداول الدفع وسياسات الاسترداد وشروط الإلغاء والمسؤوليات المالية لحج الحج.',
                'price' => 0.00,
                'image_url' => '/services/financial_policies.jpg',
                'category_id' => $categories['terms-policies'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],

            // Routes of Religious Places
            [
                'slug' => 'kaaba-masjid-haram',
                'name' => 'الكعبة والمسجد الحرام',
                'description' => 'أقدس موقع في الإسلام، موطن الكعبة. أدِ الطواف والصلوات. يقع في قلب مكة مع مداخل ومستويات متعددة.',
                'price' => 0.00,
                'image_url' => '/services/kaaba_haram.jpg',
                'category_id' => $categories['religious-places'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'mount-arafat',
                'name' => 'جبل عرفات (جبل الرحمة)',
                'description' => 'أهم موقع لحج الحج. قف في الصلاة والدعاء في يوم عرفة. يقع على بعد 20 كم جنوب شرق مكة.',
                'price' => 0.00,
                'image_url' => '/services/mount_arafat.jpg',
                'category_id' => $categories['religious-places'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'muzdalifah',
                'name' => 'مزدلفة',
                'description' => 'منطقة مقدسة بين عرفات ومنى حيث يقضي الحجاج الليلة تحت النجوم ويجمعون الحصى لطقوس الرجم.',
                'price' => 0.00,
                'image_url' => '/services/muzdalifah.jpg',
                'category_id' => $categories['religious-places'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'mina-jamarat',
                'name' => 'منى والجمرات',
                'description' => 'وادي منى حيث يقيم الحجاج في الخيام ويؤدون الرجم الرمزي للشيطان في أعمدة الجمرات الثلاثة.',
                'price' => 0.00,
                'image_url' => '/services/mina_jamarat.jpg',
                'category_id' => $categories['religious-places'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'masjid-nabawi',
                'name' => 'المسجد النبوي (المدينة)',
                'description' => 'مسجد النبي في المدينة، ثاني أقدس مسجد في الإسلام. زر قبر النبي محمد وصل في الروضة.',
                'price' => 0.00,
                'image_url' => '/services/masjid_nabawi.jpg',
                'category_id' => $categories['religious-places'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'mount-uhud',
                'name' => 'جبل أحد',
                'description' => 'جبل تاريخي في المدينة، موقع غزوة أحد. زر مقبرة الشهداء وتعلم عن التاريخ الإسلامي.',
                'price' => 0.00,
                'image_url' => '/services/mount_uhud.jpg',
                'category_id' => $categories['religious-places'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],

            // Hajj Procedure
            [
                'slug' => 'ihram-preparation',
                'name' => 'تحضير الإحرام',
                'description' => 'تعلم كيفية دخول حالة الإحرام، بما في ذلك الملابس المناسبة والنيات والقيود التي تنطبق خلال هذه الحالة المقدسة.',
                'price' => 0.00,
                'image_url' => '/services/ihram_preparation.jpg',
                'category_id' => $categories['hajj-procedure'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'tawaf-procedure',
                'name' => 'إجراءات الطواف',
                'description' => 'دليل مفصل لأداء الطواف - الدورات السبع حول الكعبة، بما في ذلك موضع البداية والاتجاه والصلوات التي يجب تلاوتها.',
                'price' => 0.00,
                'image_url' => '/services/tawaf_procedure.jpg',
                'category_id' => $categories['hajj-procedure'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'sai-procedure',
                'name' => 'إجراءات السعي',
                'description' => 'دليل خطوة بخطوة للسعي - المشي سبع مرات بين تلتي الصفا والمروة، إحياءً لذكرى بحث هاجر عن الماء.',
                'price' => 0.00,
                'image_url' => '/services/sai_procedure.jpg',
                'category_id' => $categories['hajj-procedure'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'day-arafat',
                'name' => 'إجراءات يوم عرفة',
                'description' => 'دليل كامل لأهم يوم في الحج، بما في ذلك وقت الوصول والصلوات والأدعية وإجراءات المغادرة.',
                'price' => 0.00,
                'image_url' => '/services/day_arafat.jpg',
                'category_id' => $categories['hajj-procedure'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'stoning-jamarat',
                'name' => 'رمي الجمرات',
                'description' => 'تعليمات مفصلة لطقوس الرجم الرمزي، بما في ذلك التوقيت وعدد الحجارة وإجراءات السلامة.',
                'price' => 0.00,
                'image_url' => '/services/stoning_jamarat.jpg',
                'category_id' => $categories['hajj-procedure'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'sacrifice-ritual',
                'name' => 'طقوس الذبح (القرباني)',
                'description' => 'معلومات حول طقوس الذبح أثناء الحج، بما في ذلك خيارات الذبح الشخصي أو نظام القسائم.',
                'price' => 200.00,
                'image_url' => '/services/sacrifice_ritual.jpg',
                'category_id' => $categories['hajj-procedure'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],

            // Medical Help
            [
                'slug' => 'health-tips',
                'name' => 'نصائح صحية',
                'description' => 'نصائح صحية أساسية للحجاج أثناء الحج. تعلم كيفية البقاء رطباً وإدارة التعب ومنع المرض والحفاظ على صحة جيدة طوال رحلة الحج.',
                'price' => 0.00,
                'image_url' => '/services/health_regulations.jpg',
                'category_id' => $categories['medical-help'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'call-doctor',
                'name' => 'اتصل بالطبيب',
                'description' => 'خدمة استشارة طبية طارئة. تواصل مباشرة مع أطباء مؤهلين للحصول على المشورة الطبية الفورية والمساعدة أثناء رحلة الحج.',
                'price' => 0.00,
                'image_url' => '/services/mobile_medical.jpg',
                'category_id' => $categories['medical-help'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => '+966-12-555-0123',
                'contact_type' => 'medical',
            ],

            // Forgot my Route - Emergency Contact Services
            [
                'slug' => 'hotel-gps-location',
                'name' => 'موقع GPS للفندق',
                'description' => 'إحداثيات GPS لموقع فندقك. استخدم هذا للتنقل عائداً إلى فندقك أو مشاركة موقع فندقك مع الآخرين.',
                'price' => 0.00,
                'image_url' => null,
                'category_id' => $categories['forgot-route'],
                'gps_latitude' => 21.4858,
                'gps_longitude' => 39.1925,
                'phone_number' => null,
                'contact_type' => null,
            ],
            [
                'slug' => 'contact-group',
                'name' => 'اتصل بالمجموعة',
                'description' => 'جهة اتصال طارئة لمجموعة السفر الخاصة بك. اتصل بهذا الرقم إذا كنت تائهاً أو تحتاج مساعدة من قائد المجموعة.',
                'price' => 0.00,
                'image_url' => null,
                'category_id' => $categories['forgot-route'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => '+966-12-345-6789',
                'contact_type' => 'group',
            ],
            [
                'slug' => 'contact-hotel',
                'name' => 'اتصل بالفندق',
                'description' => 'اتصال مباشر باستقبال الفندق الخاص بك. استخدم هذا للحصول على المساعدة في الاتجاهات للعودة إلى فندقك أو ترتيبات النقل.',
                'price' => 0.00,
                'image_url' => null,
                'category_id' => $categories['forgot-route'],
                'gps_latitude' => null,
                'gps_longitude' => null,
                'phone_number' => '+966-12-987-6543',
                'contact_type' => 'hotel',
            ],
        ]);
    }
}
